// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace KataSupermarket.Tests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Supermarket Bundles")]
    public partial class SupermarketBundlesFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "SupermarketBundles.feature"
#line hidden
        
        [NUnit.Framework.SetUp()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("it-IT"), "Supermarket Bundles", "Al fine di ottenere sconti e offerte\r\nIn qualità di acquirente del Supermercato\r\n" +
                    "Voglio conoscere il costo dei prodotti e le relative offerte associate", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TearDown()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("acquisto AABC e pago 120 dollari")]
        [NUnit.Framework.CategoryAttribute("Bundles")]
        public virtual void AcquistoAABCEPago120Dollari()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("acquisto AABC e pago 120 dollari", new string[] {
                        "Bundles"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Prodotto",
                        "Prezzo"});
            table1.AddRow(new string[] {
                        "A",
                        "50"});
            table1.AddRow(new string[] {
                        "B",
                        "30"});
            table1.AddRow(new string[] {
                        "C",
                        "10"});
#line 8
 testRunner.Given("il seguento listino prezzi:", ((string)(null)), table1, "Dato ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Prodotto",
                        "Quantità",
                        "Prezzo"});
            table2.AddRow(new string[] {
                        "A",
                        "2",
                        "80"});
#line 13
 testRunner.Given("le seguenti offerte:", ((string)(null)), table2, "Dato ");
#line 16
 testRunner.Given("la seguente lista di prodotti acquistati AABC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dato ");
#line 17
 testRunner.When("vado a pagare", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 18
 testRunner.Then("il prezzo totale è 120 dollari", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Allora ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("acquisto AAABC e pago 170 dollari")]
        public virtual void AcquistoAAABCEPago170Dollari()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("acquisto AAABC e pago 170 dollari", ((string[])(null)));
#line 20
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Prodotto",
                        "Prezzo"});
            table3.AddRow(new string[] {
                        "A",
                        "50"});
            table3.AddRow(new string[] {
                        "B",
                        "30"});
            table3.AddRow(new string[] {
                        "C",
                        "10"});
#line 21
 testRunner.Given("il seguento listino prezzi:", ((string)(null)), table3, "Dato ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Prodotto",
                        "Quantità",
                        "Prezzo"});
            table4.AddRow(new string[] {
                        "A",
                        "2",
                        "80"});
#line 26
 testRunner.Given("le seguenti offerte:", ((string)(null)), table4, "Dato ");
#line 29
 testRunner.Given("la seguente lista di prodotti acquistati AAABC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dato ");
#line 30
 testRunner.When("vado a pagare", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 31
 testRunner.Then("il prezzo totale è 170 dollari", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Allora ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
